/*this is header file for our own syscall mechanism*/
/*same values and in libcodasip/libsyscall.h must be used*/
/*define syscalls*/

#define CODASIP_SYSCALL_READ 1
#define CODASIP_SYSCALL_WRITE 2
#define CODASIP_SYSCALL_OPEN 3
#define CODASIP_SYSCALL_CLOSE 4
#define CODASIP_SYSCALL_LSEEK 5
#define CODASIP_SYSCALL_FSTAT 6

#define CODASIP_SYSCALL_CHOWN_UNSUPPORTED 7
#define CODASIP_SYSCALL_EXECVE_UNSUPPORTED 8
#define CODASIP_SYSCALL_FORK_UNSUPPORTED 9
#define CODASIP_SYSCALL_GETPID_UNSUPPORTED 10

#define CODASIP_SYSCALL_GETTIMEOFDAY 11

#define CODASIP_SYSCALL_ISATTY_UNSUPPORTED 12
#define CODASIP_SYSCALL_KILL_UNSUPPORTED 13
#define CODASIP_SYSCALL_LINK_UNSUPPORTED 14
#define CODASIP_SYSCALL_READLINK_UNSUPPORTED 15

#define CODASIP_SYSCALL_STAT 16

#define CODASIP_SYSCALL_SYMLINK_UNSUPPORTED 17


#define CODASIP_SYSCALL_TIMES 18

#define CODASIP_SYSCALL_UNLINK_UNSUPPORTED 19
#define CODASIP_SYSCALL_WAIT_UNSUPPORTED 20

#define CODASIP_SYSCALL_PRINTF 100 // codasip extension

#define CODASIP_SYSCALL_UNSUPPORTED 123
